services:
  # Database
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
